# -*- coding: utf-8 -*-
"""calculate_order_cost Tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xka4FNj2UrDyS9a9wlKYMXqcQMpe24fW
"""

import pandas as pd
from typing import Optional
from langchain.tools import tool

# ตั้งค่าขนส่งพื้นฐานและ % ค่าน้ำมันตามโจทย์
TRANSPORT_FEES = {
    "Talad Thai":               {"base_fee": 80,  "oil_surcharge_pct": 0.10},
    "Or Tor Kor Market":        {"base_fee": 60,  "oil_surcharge_pct": 0.08},
    "Makro":                    {"base_fee": 50,  "oil_surcharge_pct": 0.07},
    "Thai Market Bangkapi":     {"base_fee": 70,  "oil_surcharge_pct": 0.09},
    "Chatuchak Fish Market":    {"base_fee": 65,  "oil_surcharge_pct": 0.08},
}

# (โค้ดจำลองสำหรับดึงราคาที่มีอยู่เดิม)
@tool
def query_seafood_prices(query: str) -> str:
    """Query seafood prices from the database."""
    return "Dummy data"

@tool
def calculate_order_cost(items: str, shop: Optional[str] = None) -> str:
    """
    Calculate the total cost of a seafood order across different shops,
    including a transport fee that scales with oil surcharge.

    Args:
        items: A comma-separated string of items and kg, e.g., "white shrimp:2, sea bass:1"
        shop: (Optional) The specific shop name to calculate for. If None, compares all.
    """
    # 1. Parse Input Items (จัดการการเว้นวรรค และแยกชื่อสินค้ากับจำนวน)
    order_dict = {}
    for item_entry in items.split(','):
        parts = item_entry.split(':')
        if len(parts) == 2:
            req_item = parts[0].strip().lower() # แปลงเป็นพิมพ์เล็กเพื่อเทียบง่าย
            try:
                qty = float(parts[1].strip())
                order_dict[req_item] = qty
            except ValueError:
                pass

    if not order_dict:
        return "❌ Error: Could not parse items. Please format exactly like 'item:qty', e.g., 'white shrimp:2'."

    # 2. Handle Optional Shop Match (ตรวจสอบชื่อร้านค้า แบบไม่สนใจตัวพิมพ์เล็ก/ใหญ่)
    target_shop = None
    if shop:
        for valid_shop in TRANSPORT_FEES.keys():
            if valid_shop.lower() == shop.strip().lower():
                target_shop = valid_shop
                break
        if not target_shop:
            valid_list = ", ".join(TRANSPORT_FEES.keys())
            return f"❌ Error: Shop '{shop}' not found. Valid shops are: {valid_list}"

    # 3. Read CSV Data
    try:
        # รองรับการอ่านทั้งจากโฟลเดอร์หลัก และโฟลเดอร์ data/raw ตามโจทย์
        try:
            df = pd.read_csv('data/raw/seafood_prices_sample.csv')
        except FileNotFoundError:
            df = pd.read_csv('./seafood_prices_sample.csv')

        # ลบช่องว่างและอักขระพิเศษ (เช่น BOM ที่มักมาจากไฟล์ Excel) ทำเป็นพิมพ์เล็กทั้งหมด
        df.columns = [str(c).replace('\ufeff', '').strip().lower() for c in df.columns]

        # แมปชื่อคอลัมน์ให้ตรงกับไฟล์ CSV จริง
        col_mapping = {
            'item_name': 'Item',
            'shop': 'Shop',
            'price_per_kg': 'Price',
            'available': 'Available'
        }
        df.rename(columns=col_mapping, inplace=True)

        # กรณีฉุกเฉินถ้ายังหาคอลัมน์ Item ไม่เจอ ให้ไล่หาจากชื่อที่เป็นไปได้
        if 'Item' not in df.columns:
            for col in df.columns:
                if col in ['item', 'product', 'name', 'สินค้า', 'ชื่อสินค้า']:
                    df.rename(columns={col: 'Item'}, inplace=True)
                    break

    except FileNotFoundError:
        return "❌ Error: Price database file not found."

    df['Item_lower'] = df['Item'].str.lower()
    df['Shop_lower'] = df['Shop'].str.lower()

    # 4. Calculate Costs
    shops_to_check = [target_shop] if target_shop else list(TRANSPORT_FEES.keys())
    results = []
    all_found_items = set()

    for s in shops_to_check:
        shop_df = df[df['Shop_lower'] == s.lower()]

        subtotal = 0.0
        breakdown = []
        missing_in_shop = []

        for req_item, qty in order_dict.items():
            # ค้นหาชื่อสินค้าแบบ Partial Match
            match = shop_df[shop_df['Item_lower'].str.contains(req_item, na=False)]

            if not match.empty:
                row = match.iloc[0] # ดึงตัวที่เจออันแรก
                actual_item_name = row['Item']
                price_per_kg = pd.to_numeric(row['Price'], errors='coerce')

                # เช็คสถานะสินค้าว่าหมดไหมจากคอลัมน์ Available
                is_available = row.get('Available', True)
                if isinstance(is_available, str):
                    is_available = is_available.lower() == 'true'

                # เช็คว่าของหมด หรือไม่มีราคาไหม
                if pd.isna(price_per_kg) or price_per_kg <= 0 or not is_available:
                    missing_in_shop.append(f"{actual_item_name} (Out of stock)")
                else:
                    item_cost = price_per_kg * qty
                    subtotal += item_cost
                    breakdown.append(f"  - {actual_item_name}: ฿{price_per_kg:.2f} x {qty:g}kg = ฿{item_cost:.2f}")
                    all_found_items.add(req_item)
            else:
                missing_in_shop.append(f"{req_item} (Not found)")

        # คำนวณค่าส่ง: base_fee + (subtotal * oil_surcharge_pct)
        fee_info = TRANSPORT_FEES[s]
        base_fee = fee_info['base_fee']
        oil_surcharge_pct = fee_info['oil_surcharge_pct']

        # ถ้าไม่มีของเลย จะไม่คิดค่าส่ง
        transport_fee = base_fee + (subtotal * oil_surcharge_pct) if subtotal > 0 else 0
        grand_total = subtotal + transport_fee

        results.append({
            'shop': s,
            'subtotal': subtotal,
            'transport_fee': transport_fee,
            'oil_surcharge_pct': oil_surcharge_pct,
            'base_fee': base_fee,
            'grand_total': grand_total,
            'breakdown': breakdown,
            'missing': missing_in_shop
        })

    # ตรวจสอบว่ามีสินค้าไหนที่ไม่มีขายเลยในทุกร้านไหม
    not_found_anywhere = [item for item in order_dict.keys() if item not in all_found_items]

    # 5. Format & Rank Output (เรียงจากราคาถูกที่สุดไปแพงที่สุด)
    results.sort(key=lambda x: x['grand_total'])

    output_lines = []
    if not_found_anywhere:
        output_lines.append(f"⚠️ **Warning**: The following items were not found in ANY shop: {', '.join(not_found_anywhere)}\n")

    for r in results:
        output_lines.append(f"🛒 **{r['shop']}**")

        if not r['breakdown']:
            output_lines.append("  (No requested items available here)")
            output_lines.append("")
            continue

        output_lines.extend(r['breakdown'])

        if r['missing']:
            output_lines.append(f"  * Missing/Out of stock: {', '.join(r['missing'])}")

        output_lines.append("  ------------------------")
        output_lines.append(f"  Subtotal:      ฿{r['subtotal']:,.2f}")
        output_lines.append(f"  Delivery:      ฿{r['transport_fee']:,.2f} (Base ฿{r['base_fee']} + {r['oil_surcharge_pct']*100:.0f}% Oil Surcharge)")
        output_lines.append(f"  **Grand Total: ฿{r['grand_total']:,.2f}**\n")

    return "\n".join(output_lines).strip()

# --- ส่วนทดสอบแบบรับค่า User Input ---
if __name__ == "__main__":
    print("=== 🛒 ระบบคำนวณราคาอาหารทะเล ===")
    print("พิมพ์ 'exit' ในช่องรายการสินค้า เพื่อออกจากระบบ")

    while True:
        # รับค่ารายการสินค้า
        user_items = input("\n📝 ใส่รายการสินค้าและปริมาณ (เช่น white shrimp:2, sea bass:1): ")

        # เช็คว่าต้องการออกระบบไหม
        if user_items.strip().lower() == 'exit':
            print("👋 ลาก่อนค่ะ!")
            break

        # ถ้าไม่ได้พิมพ์อะไรมา ให้ถามใหม่
        if not user_items.strip():
            continue

        # รับค่าชื่อร้าน (ถ้ามี)
        user_shop = input("🏪 ระบุชื่อร้านค้า (กด Enter เพื่อข้ามและค้นหาทุกร้าน): ")
        shop_param = user_shop.strip() if user_shop.strip() else None

        print("\nกำลังคำนวณเปรียบเทียบราคา...\n")
        print("====================================")

        # เรียกใช้ฟังก์ชันด้วยค่าที่ User พิมพ์เข้ามา
        result = calculate_order_cost.invoke({'items': user_items, 'shop': shop_param})
        print(result)

        print("====================================")